DEFINES+=PROJECT_CONF_H=\"project-conf.h\"
CONTIKI_PROJECT = crypto_sample
TARGET=srf06-cc26xx
BOARD=sensortag/cc2650

all: $(CONTIKI_PROJECT)

CONTIKI_WITH_IPV6 = 1

CONTIKI = ../contiki-OS
include $(CONTIKI)/Makefile.include
